### ISSUE TITLE
perlbrew and multiple users: init is not working for other users

### ISSUE THREAD

**Issue by alanwilter** [gugod/App-perlbrew#603]
I don't know why other users don't have the folder:
`~/.perlbrew/init`

Without that, even after I had updated their `.bashrc` with:
```bash
export PERLBREW_ROOT=$UNIPROT_ROOT/conda3
. $PERLBREW_ROOT/etc/perlbrew-completion.bash
. $PERLBREW_ROOT/etc/bashrc
export PATH=$PERLBREW_ROOT/bin:$PATH
```
Only myself, the only user with `.perlbrew/init`, can see the `perl` from `perlbrew` in my `$PATH`, others still see the system perl because their `perlbrew info` returns:
```
Current perl:
Using system perl.
Shebang: #!/ebi/uniprot/production/tools/perl/perl-5.12.1/bin/perl

perlbrew:
  version: 0.82
  ENV:
    PERLBREW_ROOT: /sw/arch/conda3
    PERLBREW_HOME: /homes/trembl/.perlbrew
    PERLBREW_PATH:
    PERLBREW_MANPATH:
```
After some googling, I thought that an user doing `perlbrew init` would sort this, but, alas, nothing is happening.

Please, can someone point me out what exactly I should have done to have perlbrew install for all users? I know that if I copy my `~/.perlbrew/init` to other users this would be sorted, but alas, this is not supposed to be this way.
